Categories:
  - Connectivity
  - Development
  - Navigation
  - Security
  - System
License: GPL-3.0-only
AuthorName: hengkerzero
SourceCode: https://github.com/hengkerzero/cihuyy
IssueTracker: https://github.com/hengkerzero/cihuyy/issues
Changelog: https://github.com/hengkerzero/cihuyy/releases

AutoName: Cihuyy

RepoType: git
Repo: https://github.com/hengkerzero/cihuyy.git
Binaries: https://github.com/hengkerzero/cihuyy/releases/download/v%v/app-foss-arm64-v8a-release.apk

Builds:
  - versionName: 1.2.0
    versionCode: 13
    commit: v1.2.0
    subdir: app
    gradle:
      - foss

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.2.0
CurrentVersionCode: 13
